### ISSUE TITLE
Notify user on a position that will expire soon using FCM

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1070]
https://github.com/get10101/10101/issues/1044 introduces push notifications. 

Given we can't (yet) execute rollovers in the background we need the user to open the app. 

In order to motivate the user to open the app we want to make use of push notifications, e.g. tell him: your position is about to expire, come online now or we have to close your position. 
```[tasklist]
### Tasks
- [ ] https://github.com/get10101/10101/issues/1174
- [ ] https://github.com/get10101/10101/issues/1175
- [ ] https://github.com/get10101/10101/issues/1176
- [ ] https://github.com/get10101/10101/pull/1167
- [ ] https://github.com/get10101/10101/issues/1212
```

// edit by @bonomat // 
remove firebase crashlytics

**Comment by klochowicz** [comment]
whilst push notifications can be send when the app is in the background, they will not get delivered if the user deliberately closed the app (terminated it). The latter would occur e.g. after a phone restart, when using 'battery saver', or when they swiped out the app from the open apps menu.

**Comment by luckysori** [comment]
> whilst push notifications can be send when the app is in the background, they will not get delivered if the user deliberately closed the app (terminated it). The latter would occur e.g. after a phone restart, when using 'battery saver', or when they swiped out the app from the open apps menu.

Hmmm, that's surprising. Is there really no way that an app can send you a push notification if you have terminated it? I swear certain apps have the ability to do so on iOS.

**Comment by klochowicz** [comment]
> > whilst push notifications can be send when the app is in the background, they will not get delivered if the user deliberately closed the app (terminated it). The latter would occur e.g. after a phone restart, when using 'battery saver', or when they swiped out the app from the open apps menu.
> 
> Hmmm, that's surprising. Is there really no way that an app can send you a push notification if you have terminated it? I swear certain apps have the ability to do so on iOS.

you might be right! It might be enough to implement additional message handler, like described here:
https://stackoverflow.com/questions/66539211/fcm-push-notifications-flutter-when-app-is-terminated

**Comment by klochowicz** [comment]
Added #1104 into the scope, because this is the way we can store the IDs.

**Comment by klochowicz** [comment]
I have managed to make a PoC that sends a notification to my specific device using FCM from the coordinator.
This will allow us to have feature such as  #1211 implemented pretty much for free as soon as #1174 lands.

**Comment by klochowicz** [comment]
I'm closing this as #1297 has achieved this functionality.
