### ISSUE TITLE
Synthetic Stable Coin

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1128]
Goal: Wrap existing short position trading into a Synthetic Stable Coin feature

```[tasklist]
### Tasks
- [ ] https://github.com/get10101/10101/issues/1130
- [ ] https://github.com/get10101/10101/issues/1132
- [ ] https://github.com/get10101/10101/issues/1133
- [ ] https://github.com/get10101/10101/pull/1158
```
