### ISSUE TITLE
Add on-chain wallet 

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1177]
We need to be able to send out and receive on-chain funds from within the app.

Updated figma mocks. 

Animations are a bit broken but you get the idea :) 

https://github.com/get10101/10101/assets/224613/15516c13-a8ad-443b-8e5b-a5d26e933877

```[tasklist]
### Tasks
- [ ] https://github.com/get10101/10101/issues/1289
- [ ] https://github.com/get10101/10101/issues/1291
- [ ] https://github.com/get10101/10101/issues/313
- [ ] https://github.com/get10101/10101/issues/1411
- [ ] https://github.com/get10101/10101/issues/1538
- [ ] https://github.com/get10101/10101/issues/1290
- [ ] https://github.com/get10101/10101/issues/1396
- [ ] https://github.com/get10101/10101/issues/1288
- [ ] https://github.com/get10101/10101/issues/1537
```

**Comment by Restioson** [comment]
Related: it seems like on-chain transactions are only refreshed when the app is restarted, currently

**Comment by Restioson** [comment]
As discussed I'm assigning the subtasks here but they are still in to-do until I've started on each
