### ISSUE TITLE
Finalize trading features

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1178]
There are a few things missing to make trading feature-complete: 

```[tasklist]
### Tasks
- [ ] https://github.com/get10101/10101/issues/977
- [ ] https://github.com/get10101/10101/issues/1179
- [ ] https://github.com/get10101/10101/issues/1217
```
