### ISSUE TITLE
Resize position

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1179]
### Motivation

- Better trading UX than having to close and open to resize.
- Partially filled orders.

```[tasklist]
### Tasks
- [ ] https://github.com/get10101/10101/issues/1543
- [ ] https://github.com/get10101/10101/issues/1283
- [ ] https://github.com/get10101/10101/issues/1285
- [ ] https://github.com/get10101/10101/issues/1275
```

**Comment by holzeis** [comment]
@bonomat @luckysori can we close that epic. We support resizing now I think thats enough for that epic.

**Comment by luckysori** [comment]
Yes, let's close it!
