### ISSUE TITLE
Send/Receive USDP - Pegz

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1278]
We want to be able to send and receive USDP, i.e. reduce/close a short position to send sats around and open a new position immediately when receiving some.

```[tasklist]
### Tasks
- [ ] https://github.com/get10101/10101/issues/1441
- [x] reduce/close an open position when sending USDP
- [x] increase/open a position when receiving USDP
- [ ] hide / block trading screen in case of a stable position
- [ ] don't show USDP position in trading
- [ ] block trading if USDP position is open
```

**Comment by Restioson** [comment]
What is/are Pegz?

**Comment by bonomat** [comment]
Our synthetic stable coins :)

**Comment by Restioson** [comment]
Ah nice, that's a cute name :)

**Comment by SXBT69** [comment]
When opening a stable position, you have the corresponding short order in "orders" from the trading tab.
It would be nice having this one tagged so users know explicitly it correspond to the stable position and avoid closing it

**Comment by SXBT69** [comment]
Would it be possible to hide the USDP position in trading, keeping this stable balance while playing around and trading with the sat balance?

**Comment by holzeis** [comment]
Should be possible with https://github.com/get10101/10101/issues/1441

But then we should also add some kind of warning on the trade screen.

**Comment by luckysori** [comment]
What do we do with this epic, @bonomat, @holzeis? It's very old, so I'm not sure if the remaining items are still relevant.

**Comment by bonomat** [comment]
Closing this because it's outdated.
