### ISSUE TITLE
Finish lightning wallet features

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1323]
```[tasklist]
### Tasks
- [ ] https://github.com/get10101/10101/issues/1163
- [ ] https://github.com/get10101/10101/issues/180
- [ ] https://github.com/get10101/10101/issues/74
- [x] Redesign create / share invoice screen
- [x] Redesign send payment screen
- [x] Wait if payment was successful before giving feedback to user
- [ ] https://github.com/get10101/10101/issues/1304
- [ ] https://github.com/get10101/10101/issues/1561
- [ ] https://github.com/get10101/10101/issues/1407
- [ ] https://github.com/get10101/10101/issues/1596
- [ ] Refresh lightning wallet when payment is sent
- [ ] https://github.com/get10101/10101/issues/1632
- [ ] Fetch scorer from prober service
```
