### ISSUE TITLE
Add explanation about reserved collateral for on-chain fees when opening a position

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1496]
It currently looks odd that when you open a new position that 3,716 sats are additionally removed from your balance for the on-chain transaction reserve.

We should at least explain / show these fees / collateral somewhere.
```[tasklist]
### Tasks
- [ ] Add additional transaction into history showing the locked up on-chain tx fee reserve
- [ ] Remove additional locked up on-chain tx fee transaction when position closed or channel is closed
- [ ] Add details card to the locked up on-chain tx fee explaining what this is about
```

**Comment by holzeis** [comment]
@bonomat Alternatively we could also just show it on the balance and look at it like the reserve kept in the channel, that can't be spent while the channel is open. Its a concept that's already introduced by lightning, so I guess users may understand?

**Comment by bonomat** [comment]
> Its a concept that's already introduced by lightning, so I guess users may understand?

I'm not sure if many understand this as not every wallet has it. 

> @bonomat Alternatively we could also just show it on the balance and look at it like the reserve kept in the channel, that can't be spent while the channel is open.

I would show it on the position and remove the "reserve" so that the user can spend everything. 
On the position we can explain that this amount is reserved for the tx fee.

**Comment by holzeis** [comment]
> > Its a concept that's already introduced by lightning, so I guess users may understand?
> 
> 
> 
> I'm not sure if many understand this as not every wallet has it. 

Phoenix does have it..

> > @bonomat Alternatively we could also just show it on the balance and look at it like the reserve kept in the channel, that can't be spent while the channel is open.
> 
> 
> 
> I would show it on the position and remove the "reserve" so that the user can spend everything. 
> 
> On the position we can explain that this amount is reserved for the tx fee. 

The ln reserve can't be removed (min is 1000 sats) unless we change it on our fork.
