### ISSUE TITLE
App outbound payments often fail

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#1690]
We replaced `P2pGossipSync` with `RapidGossipSync` and that solved some problems but not all. Some app users still encounter problems making outbound payments.

```[tasklist]
### Things that could be done
- [x] Print channel details when payment fails
- [ ] https://github.com/get10101/10101/pull/1707
- [x] Deploy a release with `rust-lightning:0.0.117` to get more verbose TRACE logs on error.
- [x] Allow app users to delete network graph and sync via RGS from scratch. https://github.com/get10101/10101/pull/1744
- [ ] https://github.com/get10101/10101/issues/1632
```

**Comment by bonomat** [comment]
https://github.com/get10101/10101/pull/1744 was recently merged which might improve things.

**Comment by luckysori** [comment]
No longer relevant.
