### ISSUE TITLE
MVP Epic

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#215]
This epic covers what we want to see in the MVP:

1. Reckless-mainnet MVP
    1. Spend as little time building this as possible
    2. Retrieve funds from any state
        1. We don’t want to get into a state where we need to prune the `data` directory of the coordinator because this would mean we would lose funds
    3. Positions are open for 24h
        1. we try to collaboratively close
        2. if does not work, we force close the channel
    4. Configuration: we need to figure out the right configuration to
        1. return funds from Lightning channels as fast as possible
        2. return funds from a DLC channel as fast as possible

See details [in Notion](https://www.notion.so/get10101/Q2-23-b8715317f0af4232ad78616ec1932472)

## App

- [ ] https://github.com/get10101/10101/issues/347
- [x] https://github.com/get10101/10101/issues/67
- [x] https://github.com/get10101/10101/issues/68
- [x] https://github.com/get10101/10101/issues/128
- [x] https://github.com/get10101/10101/issues/132
- [x] https://github.com/get10101/10101/issues/134
- [x] https://github.com/get10101/10101/issues/73
- [x] #220
- [x] https://github.com/get10101/10101/issues/168

## Maker

- [ ] #217
- [x] #216

## Orderbook

- [x] #219
- [x] #218

## Coordinator

- [x] #226
- [x] https://github.com/get10101/10101/issues/51

## Global tickets

- [x] https://github.com/get10101/10101/issues/50
- [ ] #221

### App Nice to Have for MVP

- [ ] https://github.com/get10101/10101/issues/63
- [x] https://github.com/get10101/10101/issues/64
- [ ] https://github.com/get10101/10101/issues/346
- [ ] https://github.com/get10101/10101/issues/74
- [ ] https://github.com/get10101/10101/issues/137
- [x] https://github.com/get10101/10101/issues/131
- [ ] https://github.com/get10101/10101/issues/163
- [ ] https://github.com/get10101/10101/issues/180

### Resilience

Bugs that will require to wipe the coordinator or reinstall the app

- [x] https://github.com/get10101/10101/issues/299
- [x] https://github.com/get10101/10101/issues/308
- [x] https://github.com/get10101/10101/issues/309
- [x] https://github.com/get10101/10101/issues/333
- [x] https://github.com/get10101/10101/issues/336
- [x] https://github.com/get10101/10101/issues/352
- [x] https://github.com/get10101/10101/issues/359

### Maker Nice to Have for MVP

- [ ] Hedge position

## Perpetual

Can be postponed till post MVP

- [ ] https://github.com/get10101/10101/issues/133

**Comment by da-kami** [comment]
I updated this ticket: 

- Moved https://github.com/get10101/10101/issues/51 to be implemented for the coordinator
- Added https://github.com/get10101/10101/issues/347 for the app
- Some minor ticket-splits for the app to convey better what is implemented and what not.

**Comment by bonomat** [comment]
Unsorted TODOs: 

- [ ] cap the channel size 
- [ ] form validation: allow the user to do only possible things (e.g. check if there is enough channel balance)
- [ ] communicate with the user if a channel is not usable anymore because it is unbalanced. 
	- inform the user to inform us
- [ ] referral: if we give the user 2k sats, can the user open a position or do anything?
	- Do we need a cap for referral payments because we cannot extend an existing channel?
- [ ] in app tracking
	- user clicked buy/sell, user clicked confirm
	- user clicked close position
	- how often do they open the app
	- e.g. the app sends telemetries to the coordinator
- [ ] Show the expiry in the position and when creating an order (e.g. 00:00 every day)
- [ ] add push notification to tell the user: your trade is over, please open app to receive loss/profit
	- when the user opens the app, we collaboratively close the position at the price at expiry time
	- we need a background task which checks for (close to) closed positions to send a notification to the users phone
- [ ] check if numbers are adding up (e.g. P/L)
- [ ] error handling: the user does not know anything if a position failed. If something failed tell user: please share logs with us
- [ ] startup: fix splash screen of death
	- e.g. add a text: we are loading, please wait...
	- add Beta tag
	- ~add a welcome wizard and load in the background~
- [ ] closing the screen should show the _create buy/sell_ screen. Don't just close the position but show order overaly
- [ ] (optional) send on-chain funds
- [ ] remove `30 fees` and mention that while in beta we do not charge any orderbook fee
- [ ] change max leverage to 5
- [ ] welcome wizard: https://github.com/get10101/10101/issues/63
- [ ] wallet backup: https://github.com/get10101/10101/issues/63
- [ ] make send off-chain more beautifully: adhere to Figma mocks
- [ ] ~send on-chain screen ~ can be postponed if wallet can be used in different app
- [ ] check if we can recover funds from blue wallet

**Comment by bonomat** [comment]
I believe we can close this epic even though not all tickets have been done. Let's focus on [Q3](https://github.com/get10101/10101/issues/793) instead.
