### ISSUE TITLE
10101 in WASM

### ISSUE THREAD

**Issue by Restioson** [get10101/10101#2166]
```[tasklist]
### Tasks
- [x] #2059
- [x] #2094
- [ ] https://github.com/get10101/10101/issues/2209
- [ ] https://github.com/get10101/10101/issues/2167
- [ ] Replace instances of blocking code in ln-dlc-node
- [ ] https://github.com/get10101/10101/issues/2168
- [ ] https://github.com/get10101/10101/issues/2169
- [ ] https://github.com/get10101/10101/issues/2170
```

**Comment by bonomat** [comment]
We changed direction and put this on ice for now.
