### ISSUE TITLE
Receive via Lightning flow

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#2537]
Allow users to on-board using bolt11 invoices

```[tasklist]
### Tasks
- [ ] https://github.com/get10101/10101/issues/2540
- [x] connect coordinator with LND to get a new invoice
- [x] connect coordinator with LND to check invoice status
- [ ] app->coordinator API: I want to fund with Lightning
- [ ] update rust-dlc to support single sided DLC channels
- [ ] update rust-dlc to support 0-conf
```

**Comment by bonomat** [comment]
Afaik this was all done
