### ISSUE TITLE
MVP: Figma Designs

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#43]
Scope:

- [x] Create separate flow for the Designs and flow of the MVP wireframe (move copy of current flow to archive section)
- [x] Remove the stable sats use case (MVP does not contain stable sats wallet)
- [x] https://github.com/get10101/10101/issues/37
- [x] https://github.com/get10101/10101/issues/42
- [x] https://github.com/get10101/10101/issues/54
- [x] https://github.com/get10101/10101/issues/52
- [x] https://github.com/get10101/10101/issues/53
- [x] https://github.com/get10101/10101/issues/38
- [x] https://github.com/get10101/10101/issues/39
- [x] https://github.com/get10101/10101/issues/40
- [x] https://github.com/get10101/10101/issues/41
- [x] https://github.com/get10101/10101/issues/56
- [x] #58
- [x] #59
- [ ] #60

**Comment by da-kami** [comment]
I moved the flow of the `MVP` into a section called `MVP` - I kept a copy of the previous flow in `PreMVP` for now.
The stable sats use case was removed in `MVP` already.

**Comment by da-kami** [comment]
Decisions for the MVP design:

1. We integrate the Home Screen into the wallet for now, because there is no clear need for the home screen. 
    1. 
    2. The design *has* to allow easily adding a home screen in case we want a view that combines the wallet balance with the trading balance into a "depot value" view. 
2. There is only one `Wallet` for now, but we separate the on-chain from the off-chain balance. (similar to Zeus)
    1. We show a combined balance consisting of the on- and off-chain balance.
    2. For now the 10101 wallet is *not* designed to allow multiple on- and off-chain wallets. It is not expected that we will ever allow multiple off-chain wallets. We could eventually allow multiple on-chain wallets by changing he look and feel of the `Wallet` tab to allow creating wallets and swiping between them.
    3. The `Stable Sats` use case is expected to be added as a separate tab in the bottom navigation bar, like the `Trade` tab. Stable sats is one of our main features and not "just a wallet". The design of the `Stable Sats` tab is not decided yet - it might still look like a USD wallet.
4. We implicitly integrate the trading wallet into the `Trade` screen. 
    1. There is no separate trading wallet, and no explicit step to "move funds for trading". 
    4. When trading we implicitly move funds to the trading tab as needed, example:
        1. The user funds the Lightning wallet with 1000 sats
        2. The user opens a Buy/Long position using 500 sats; a Buy/Long order is being created
        3. Upon the the order getting filled the transaction history of the Lightning wallet will show `-500 sats` for the filled order. 
        5. The user closes the Buy/Long position (i.e. a Sell/Short order is being created) 
        6. Upon the the order getting filled the transaction history of the Lightning wallet will show `-500 sats` for the filled order.
    4. For the MVP the assumption is that the market orders of the app are always filled completely (no partial filling)
    5. The channel split is updated in the background. The assumption is that this is not an expensive action so this should be fine.
        1. In case this is not feasible we can consider adding a separate step to move funds from `Wallets` to `Trade`. If we do so the trading wallet should still be represented as part of the `Trade` tab.


Screenshot that shows the concept:

![image](https://user-images.githubusercontent.com/5557790/215033878-3da85b05-dd03-49d9-87f2-bd8d5ab01255.png)

Note: Some widgets will need to be beautified (bottom bar, the trade buy/sell buttons, ...).

Other notes:

- The scanner was moved to the top of the wallet screen (similar to the design in Zeus). Since our wallet is a trading wallet the scanner is not the most important action, but should be accessible. 
- The FAB on the bottom contains Send/Receive actions. Upon clicking either action in the FAB we open a wizard where the user has to select to send/receive on-or offchain.
- The combined balance can be closed (the on-chain and off-chain balance tiles are hidden then). The app should remember the state, i.e. if the user keeps them open it should remain open upon restarting the app.
- The on-chain / off-chain balance tiles have have the quick actions to send/receive (similar to before), which skips having to select a "wallet to be funded".
- The initial "security" setup and "fund wallet" tiles will be shown in the "Wallet" screen. (this is not depicted in the screenshot above)
-

**Comment by bonomat** [comment]
Most of it was done
