### ISSUE TITLE
Trade Feature

### ISSUE THREAD

**Issue by 1010Tom** [get10101/10101#68]
Includes 
- create market order, 
- list position, 
- list orders and trades, 

https://user-images.githubusercontent.com/88702308/215654839-933f50f4-5d1b-4025-a608-38cf6ab2ef05.mov

After merging the initial rampup (#104) these are some specific tickets to complete the trade screen:

must:

- [x] https://github.com/get10101/10101/issues/129
- [x] https://github.com/get10101/10101/issues/130
- [x] https://github.com/get10101/10101/issues/172

**Comment by bonomat** [comment]
closed in favor of https://github.com/get10101/10101/issues/215. Open tasks have been migrated to the new epic
