### ISSUE TITLE
Task list example

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#939]
```[tasklist]
### My tasks
- [ ] Create sample task list
- [ ] https://github.com/get10101/10101/issues/936 (just a sample)
```
```[tasklist]
### Some other tasks
- [ ] Don't make me tick the box
- [x] I did tick the box
```

**Comment by bonomat** [comment]
Was just an example :)

**Comment by klochowicz** [comment]
cool, nice new feature! thanks for sharing
