### ISSUE TITLE
Maker

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#972]
The maker hedges his position on bitmex. Any matched order received from the coordinator, will simply get created as position skipping the dlc setup. That simplifies the overall process and safes costs, as the maker and the coordinator are anyways both in control of 10101.

```mermaid
sequenceDiagram

participant b as BitMex
participant m as Maker
participant c as Coordinator
participant o as Orderbook
participant t as Taker


m ->> o: create limit order

t ->> o: market order
o -->> o: match maker and taker

o ->> c: execute match


c -> t: Setup DLC channel

c ->> m: Inform match

m ->> m: Adapt hedge position

m ->> b: Update order

```

```[tasklist]
### Tasks
- [ ] https://github.com/get10101/10101/issues/1032
- [ ] https://github.com/get10101/10101/issues/919
- [ ] https://github.com/get10101/10101/issues/973
- [ ] https://github.com/get10101/10101/issues/974
- [ ] https://github.com/get10101/10101/issues/926
- [ ] https://github.com/get10101/10101/issues/1036
- [x] Discussion on position expiry: https://github.com/get10101/10101/discussions/1038
- [ ] https://github.com/get10101/10101/issues/1172
- [ ] https://github.com/get10101/10101/issues/1173
```

```[tasklist]
### Optional
- [ ] https://github.com/get10101/10101/issues/227
- [ ] https://github.com/get10101/10101/issues/910
```

**Comment by da-kami** [comment]
Note (nothing to action here):

As the sequence diagram outlines, the maker is only notified once the match with trader was executed (i.e. the DLC is successfully set up between coordinator and the taker).
Note that this step will eventually be obsolete - once the maker reasons about it's own position (and sets up DLCs with the coordinator) the coordinator will not have to notify the maker at this point, but the maker is consuming order matches from the orderbook as the taker does.
You might want to capture the *eventual complete* flow somewhere separate as well so it is clear how this should evolve.

**Comment by bonomat** [comment]
>  Note that this step will eventually be obsolete - once the maker reasons about it's own position (and sets up DLCs with the coordinator) the coordinator will not have to notify the maker at this point, but the maker is consuming order matches from the orderbook as the taker does.

This is what was meant with the step `inform match`: the orderbook notifies the maker-daemon about a match being found. The maker can then _assume_ that the DLC protocol will be successful and can start hedging.

**Comment by bonomat** [comment]
still valid and almost done.

**Comment by holzeis** [comment]
@bonomat all tickets are closed or done. Can we close this epic?

**Comment by bonomat** [comment]
This epic is done. We will need a follow-up ticket to make the maker feature complete.
