### ISSUE TITLE
Stability

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#975]
```[tasklist]
### Tasks
- [ ] https://github.com/get10101/10101/issues/874
- [ ] https://github.com/get10101/10101/issues/797
- [ ] https://github.com/get10101/10101/issues/779
- [ ] https://github.com/get10101/10101/issues/845
- [ ] https://github.com/get10101/10101/issues/846
- [ ] https://github.com/get10101/10101/issues/842
- [ ] https://github.com/get10101/10101/issues/807
- [ ] https://github.com/get10101/10101/issues/885
- [ ] https://github.com/get10101/10101/issues/313
```

**Comment by bonomat** [comment]
We don't need an epic for this.
