### ISSUE TITLE
Perpetual Futures

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#977]
At the moment we have an expiry timestamp on every position. After it has been expired we will trigger a collaborative closure once the user is back online. With perpetual positions we want to add the possibility to "rollover" a position and extend it. 
```[tasklist]
### Tasks
- [ ] https://github.com/get10101/10101/issues/1068
- [ ] https://github.com/get10101/10101/issues/1069
- [ ] https://github.com/get10101/10101/issues/1044
- [ ] https://github.com/get10101/10101/issues/1185
- [ ] https://github.com/get10101/10101/issues/1070
- [ ] https://github.com/get10101/10101/issues/1071
- [ ] https://github.com/get10101/10101/issues/133
- [ ] https://github.com/get10101/10101/issues/1123
- [ ] https://github.com/get10101/10101/issues/1184
```

**Comment by holzeis** [comment]
Below a proposal of how perpetual futures could look like for the users. I'

```mermaid
sequenceDiagram

actor u as User
participant a as App
participant c as Coordinator

Note right of a: Position is about to expire. e.g. in 2 hours

c->>u: Push notification: Come online to rollover your position.
u->>a: Starts 10101 app
a-->>u: Show dialog for extending position

alt Extend position 
a-->>u: Show finished extending position
else Close position
a->c: collaborative close position
a->>a: Remove position
a-->>u: Show finished close position
end






```

**Comment by klochowicz** [comment]
what's the advantage of asking the user a question instead of extending it automatically until the user wants to close the trade?

**Comment by bonomat** [comment]
Mostly done :)
